sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start"
  - docker build -t kimtaeho/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true kimtaeho/docker-react-sample npm run test -- --coverage

after_success:
  - echo "Test Success"